<?php

namespace AppBundle\Repository;

/**
 * DadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DadRepository extends \Doctrine\ORM\EntityRepository
{
}
